firefliesai/.github

.github/workflows/build-and-deploy.yaml

Build and Dispatch to GitOps repository workflow template.
[Mailin Server build uses this workflow](https://github.com/firefliesai/mailin-server/runs/4221825800)
xxx
xxx
xxx
xxx

Chore sc 13388 GitHub action workflow templates

---

.github/workflows/build-and-deploy.yaml
.github/workflows/build-and-structure-test.yaml
.github/workflows/structure-test.yaml

Add structure test for containerized app
[Successful Test](https://github.com/firefliesai/mailin-server/runs/4264811551)
[Failed Test](https://github.com/firefliesai/mailin-server/runs/4264884175)
A simple way to test containerized application for its structure. For example, is the image containing necessary binary? is the configuration file available on the image?. This also will be very helpful for testing node migration.
-

Add structure test to container

---

.github/workflows/build-and-deploy.yaml
.github/workflows/structure-test.yaml

Enable action cache for buildkit cache to speed up build
[build with cache enabled](https://github.com/firefliesai/download-ff/runs/4282093007) -- 1m 36s
[build without cache](https://github.com/firefliesai/download-ff/runs/4281900620) -- 2m 23s
xxx
xxx
xxx
xxx

Buildkit cache

---

.github/workflows/build-and-deploy.yaml

- add labels on build
- add labels on build so it will be listed on repo

metadata labels

---

pull_request_template.md

- Add the type of change section in the PR template
[Slack thread](https://firefliesapp.slack.com/archives/CPQCRMTU4/p1644523474312249)
[Shortcut story](https://app.shortcut.com/fireflies/story/17217/add-type-of-change-in-global-pr-template)

Add the type of change section in the PR template

---

.github/workflows/build-and-deploy.yaml
.github/workflows/structure-test.yaml

Add `buildArgs` parameters for adding environment variables on build phase
[Build and Deploy](https://github.com/firefliesai/mailin-server/runs/5595512332?check_suite_focus=true)
[PR Checker](https://github.com/firefliesai/landing-ff/runs/5595469717?check_suite_focus=true)
xxx
xxx
xxx
xxx

Add buildArgs parameters

---

.github/workflows/build-and-deploy.yaml

- add steps to determine target cluster
- configure encoding

feature sc 22590 refactor github action staging dispatch event

---

.github/workflows/build-and-deploy.yaml

- add tagPrefix options to build tag
- fix params type
- lack of `{`
- include prefix on output
- output full sha tags
- tag image with full sha
- use pr head sha on pull request

tagPrefix params

---

.github/workflows/build-and-deploy.yaml
.github/workflows/structure-test.yaml

Add capability to supply build context into the docker build steps. This capability allow us to build container image from different directory than root
Being used on other repository to do PR checker https://github.com/firefliesai/models-fireflies/runs/7514060921?check_suite_focus=true
xxx
xxx
xxx
xxx

Add context build params

---

.github/workflows/gitflow-create-release.yml
.github/workflows/gitflow-post-release.yml

See https://www.notion.so/fireflies/Automate-release-changelog-and-announcement-daf14aa131974cb291212e544359d018
xxx
xxx
xxx
xxx
xxx

Improve gitflow workflow action and add to [sc-26453]

---

.github/workflows/gitflow-post-release.yml

Add puppet-masters IDs
xxx
xxx
xxx
xxx
xxx

Add slack ids for automate release

---

.github/workflows/build-and-deploy.yaml

This is due to the need of test custom branch, before merging in staging, in staging environment.
xxx
xxx
xxx
xxx
xxx

Allow custom branch be deployed to staging cluster

---

.github/workflows/build-and-deploy.yaml

Fix unary comparison error
```bash
/home/runner/work/_temp/91d9bf59-4795-401b-b3a5-d7c8eb1f1c94.sh: line 5: [: !=: unary operator expected
```
xxx
xxx
xxx
xxx
xxx

fix: fix tag calculation

---

.github/workflows/build-and-deploy.yaml

Automatically add additional dispatch to k8s-production for backward compatibility on new k8s-production migration.
xxx
xxx
xxx
xxx
xxx

feat: add additional dispatch event to k8s-production

---

.github/workflows/build-and-deploy.yaml
.github/workflows/structure-test.yaml

- Update github actions to latest version
**Rmove these warnings because of the outdated workflows**
I tested these workflows inside `payments-ff`
**Structure test**
https://github.com/firefliesai/payments-ff/actions/runs/4020623758/jobs/6908744709
**Build and Deploy**
https://github.com/firefliesai/payments-ff/actions/runs/4020643697

Update github actions to latest version

---

.github/workflows/build-and-deploy.yaml

context: https://github.com/firefliesai/codex-ff/pull/144
Ideally, whisper-gpu should have its own Dockerfile & CI build in codex-ff repo. It is a large docker image.

chore: add dockerFilePath option to specify Dockerfile path

---

pull_request_template.md

- Add `What are the requirements to deploy to production?` section to PR template
[Slack thread](https://firefliesapp.slack.com/archives/CKVS2CUKY/p1677795784963449?thread_ts=1677794890.802909&cid=CKVS2CUKY)

Add new section to PR template

---

.github/workflows/gitflow-post-release.yml

- Add sumit and carlos to release flow

Add Sumit and Carlos to release flow

---

.github/workflows/gitflow-post-release.yml

Adds slack id and GitHub username for feature rollout mapping

add some members to list of feature rollout user mappings

---

.github/workflows/gitflow-post-release.yml

release workflow is not working for all repos because of an extra comma
xxx
xxx
xxx
xxx
xxx

Fix release workflow

---

.github/workflows/build-and-deploy.yaml

fix GITHUB_TOKEN permission issue

---

.github/workflows/build-and-deploy.yaml

fix permission

---

.github/workflows/build-and-deploy.yaml

remove permissions

---

.github/workflows/gitflow-post-release.yml

chore: add Ashim to release flow

---

.github/workflows/gitflow-post-release.yml

chore: add Haziq and Shivam to maps

---

.github/workflows/gitflow-post-release.yml

- Add henry to release process
- Fix user id for Carlos and Sumit

Add henry to release process

---

.github/scripts/auto_announce.js
.github/scripts/auto_release.js
.github/workflows/auto_announce.yml
.github/workflows/auto_release.yml

- it creates a reusable workflow for auto deployment and announcement on slack
xxx
xxx
xxx
xxx
xxx

Auto deployment and slack announcement workflow

---

.github/workflows/auto_announce.yml
.github/workflows/auto_release.yml

- it imports javascript files for workflow logic
xxx
xxx
xxx
xxx
xxx

Nest workflow script files in checkout

---

.github/workflows/auto_release.yml

- It lists files in the workflow directory for debugging
xxx
xxx
xxx
xxx
xxx

List files in the workflow directory

---

.github/workflows/auto_release.yml

- It logs the context object for debugging
xxx
xxx
xxx
xxx
xxx

Log context for debugging

---

.github/workflows/auto_release.yml

- It adds inputs to context object
xxx
xxx
xxx
xxx
xxx

Add inputs to context object

---

.github/scripts/auto_announce.js
.github/scripts/auto_release.js
.github/workflows/auto_announce.yml
.github/workflows/auto_release.yml

- It returns an output for the create_release workflow call
xxx
xxx
xxx
xxx
xxx

Set output for workflow for when a new deployment is made

---

.github/scripts/auto_release.js
.github/workflows/auto_release.yml

- it adds logs to debug the summaries workflow
xxx
xxx
xxx
xxx
xxx

Add logs to debug `generate_summaries` workflow

---

.github/scripts/auto_release.js

- it refactors the code that checks if a commit is a merge commit for a PR
xxx
xxx
xxx
xxx
xxx

Refactor checks for PR commit message

---

.github/scripts/auto_announce.js
.github/workflows/auto_release.yml

- It checks the error for when a release has never been made
xxx
xxx
xxx
xxx
xxx

Add logs to debug create_release workflow

---

.github/scripts/auto_announce.js

- It checks the error for when a release has never been made
xxx
xxx
xxx
xxx
xxx

Add logs to debug `create_release` workflow

---

.github/scripts/auto_announce.js
.github/scripts/auto_release.js

- It updates the engineer slack ID array
- It removes debug logs
xxx
xxx
xxx
xxx
xxx

Add fisfat slack ID

---

.github/scripts/auto_announce.js
.github/workflows/auto_announce.yml

- It adds more engineer IDs to the auto mated slack announcement
xxx
xxx
xxx
xxx
xxx

Add more engineer IDs

---

.github/scripts/auto_announce.js
.github/workflows/auto_announce.yml

- It refactors the logic for generating the release notes.
xxx
xxx
xxx
xxx
xxx

Refactor code for generating release notes

---

.github/workflows/auto_announce.yml

- Fix syntax error in commenting JS code
xxx
xxx
xxx
xxx
xxx

Fix error in generating release notes

---

.github/scripts/auto_announce.js

- It removes the PR list from the release notes
xxx
xxx
xxx
xxx
xxx

Remove redundant section from release notes

---

.github/scripts/release.yml
.github/workflows/auto_announce.yml

- It adds support for release configuration files 
xxx
xxx
xxx
xxx
xxx

Add support for release config

---

.github/workflows/auto_announce.yml

- It checks that the release config fie in checkout
xxx
xxx
xxx
xxx
xxx

Debug release config file

---

.github/release.yml

- It creates the default release notes config
xxx
xxx
xxx
xxx
xxx

Add a default release config

---

.github/workflows/gitflow-post-release.yml
.github/workflows/gitflow-release.yml

Fix the duplicate issue when running gitflow-release
xxx
xxx
xxx
xxx
xxx

Fix gitflow-release

---

.github/scripts/gitflow-release.js
.github/workflows/gitflow-release.yml

- Fix semver versioning
- If `package_json_update_version` is set to true, it will update the repo package.json `version` field and commit it to the release branch
xxx
xxx
xxx
xxx
xxx

gitflow-release: fix versioning and add auto commit package json version

---

.github/workflows/gitflow-post-release.yml

chore: add robert slack id

---

.github/workflows/auto_release.yml

- Fix auto release
Github doesn't allow to send secrets/envs as `inputs` as that would leak secrets, so we will use as envs
- #68

Fix auto release

---

.github/scripts/PR_reviewer.js
.github/workflows/PR_reviewer.yml

This PR updates the workflow to run the PR reviewer even if the cache step cannot be run. It also fixes an error happening in some repositories because of how the Octokit package is imported, so from now on a dynamic import is being used instead.
Tests run pointing to this branch as ref:
- when the step to save description to file fails (invalid char, no EOF in PR description), we run the reviewer anyway: https://github.com/firefliesai/connector-ff/actions/runs/9613700160/job/26516968633
- when cache hit, no need to run reviewer: https://github.com/firefliesai/connector-ff/actions/runs/9613634157/job/26516765333
- when cache miss, runs reviewer: https://github.com/firefliesai/connector-ff/actions/runs/9613556995/job/26516535145
xxx
xxx
xxx
xxx
xxx

chore: update PR reviewer workflow

---

.github/scripts/auto_announce.js
.github/scripts/auto_release.js
.github/workflows/gitflow-post-release.yml
.github/workflows/gitflow-release.yml

- Add new devs to the github list

Add new devs to the github list

---

.github/scripts/auto_announce.js
.github/workflows/gitflow-post-release.yml
.github/workflows/gitflow-release.yml

Add devs to github list

---

.github/scripts/PR_reviewer.js

chore(pr-reviewer): add missing slack channel

---

.github/scripts/auto_release.js

Initiative: to support more cases that people would compose in "What does this PR do" in each PR and organize them well in the Release Summary section in the deployment PR
slack: https://firefliesapp.slack.com/archives/CKD0K54LW/p1724748417556279
We can merge this, or update the used yml file in any repo to test this, without merging this, e.g. `uses: firefliesai/.github/.github/workflows/auto_release.yml@feat-sc-59512-try-to-improve-auto-release-js`
left to do
After this Experimental Release Summary is stable, we can choose (i) replace Release Summary and modify the following processing auto_announce.yml, (ii) OR keep "Release Summary" for auto_announce.yml but make it becomes hidden in GitHub deployment PR and only use "Release Summary" for Slack announcement.   …

Add Experimental Release Summary

---

.github/scripts/auto_release.js

- Fixes auto-release.js
xxx
xxx
xxx
xxx
xxx

fix: add missing local variable pullRequest

---

.github/scripts/auto_release.js

fix: return final string draft

---

.github/scripts/auto_release.js

xxx
This is to fix the issues found in 
- https://github.com/firefliesai/codex-ff/pull/1229. 
And please check https://github.com/firefliesai/.github/pull/87/commits
xxx
xxx
xxx

improve auto announce js for expermental release summary again

---

.github/scripts/PR_reviewer.js
.github/workflows/PR_reviewer_test.yml

This PR improves the existing Slack notification system by adding structured messages, detailed logging of pull requests, and a dynamic priority line based on the review's risk assessment. Additionally, it extends the system to handle file changes from GitHub, displays the file names and diff, and assigns a priority emoji to highlight the level of risk (Low, Medium, High).
Create or update a pull request and trigger the Slack notification.
Check the Slack message for:
A summary of the PR review.
A priority line indicating the review's risk level with the appropriate emoji.
File changes, including file names and a brief diff.
Verify that the priority level and emoji are determined correctly based on the review content.
Ensure that detailed logging is …

Feature sc 60183 pr reviewer enhancements

---

.github/workflows/PR_reviewer.yml

- Fix not installing all the dependencies for PR reviewer
[Slack thread](https://firefliesapp.slack.com/archives/CKD0K54LW/p1727785677405699)

Fix not installing all the dependencies for PR reviewer

---

.github/workflows/PR_reviewer.yml

- Pin deps from PR Reviewer
There was a bug with `node-fetch` being ESM only now

Pin deps from PR Reviewer

---

.github/scripts/PR_reviewer.js

Replace GITHUB_TOKEN with GTP_TOKEN

---

.github/scripts/PR_reviewer.js

Tag security officers when the priority is set to high as call to action
xxx
xxx
xxx
xxx
xxx

feat: add security officers tag to high priority review

---

.github/scripts/auto_announce.js
.github/workflows/gitflow-post-release.yml
.github/workflows/gitflow-release.yml

- Add gui to the github list
[Slack thread](https://firefliesapp.slack.com/archives/D081P4N5C3X/p1733755417663009)

Add gui to the github list

---

.github/workflows/PR_reviewer_test.yml

fix: path to file reviewer

---

.github/workflows/PR_reviewer_test.yml

fix: path on dep install

---

.github/workflows/PR_reviewer_test.yml

fix: working dir
